export const GENRE_ITEMS = [
	{ label: 'Action' },
	{ label: 'Action & Adventure' },
	{ label: 'Adventure' },
	{ label: 'Animation' },
	{ label: 'Comedy' },
	{ label: 'Crime' },
	{ label: 'Documentary' },
	{ label: 'Drama' },
	{ label: 'Family' },
	{ label: 'Fantasy' },
	{ label: 'History' },
	{ label: 'Horror' },
	{ label: 'Kids' },
	{ label: 'Music' },
	{ label: 'Mystery' },
	{ label: 'News' },
	{ label: 'Reality' },
	{ label: 'Romance' },
	{ label: 'Sci-Fi & Fantasy' },
	{ label: 'Science Fiction' },
	{ label: 'Soap' },
	{ label: 'Talk' },
	{ label: 'Thriller' },
	{ label: 'TV Movie' },
	{ label: 'War' },
	{ label: 'War & Politics' },
	{ label: 'Western' },
];

export const COUNTRY_ITEMS = [
  { label: 'Argentina' },
  { label: 'Australia' },
  { label: 'Austria' },
  { label: 'Belgium' },
  { label: 'Brazil' },
  { label: 'Cananda' },
  { label: 'China' },
  { label: 'Czech Republic' },
  { label: 'Denmark' },
  { label: 'Finland' },
  { label: 'France' },
  { label: 'Germany' },
  { label: 'Hong Kong' },
  { label: 'Hungary' },
  { label: 'India' },
  { label: 'Ireland' },
  { label: 'Israel' },
  { label: 'Italia' },
  { label: 'Japan' },
  { label: 'Luxembourg' },
  { label: 'Mexico' },
  { label: 'Netherlands' },
  { label: 'New Zeeland' },
  { label: 'Norway' },
  { label: 'Poland' },
  { label: 'Romania' },
  { label: 'Russia' },
  { label: 'South Africa' },
  { label: 'South Korea' },
  { label: 'Spain' },
  { label: 'Switzerland' },
  { label: 'Taiwan' },
  { label: 'Thailand' },
  { label: 'United Kingdom' },
  { label: 'United States of America' },
];

export const SIDEBAR_FOOTER_LINKS = [
  { label: 'Term of service', href: "/terms" },
  { label: 'DMCA', href: "/" },
  { label: 'Contact', href: "/contact" },
  { label: 'Sitemap', href: "/" }
];